#!/usr/bin/expect -f

set device [lindex $argv 0];
set uuid  [lindex $argv 1];
set notifies  [lindex $argv 2];
set timeout 60
spawn bluetoothctl
send -- "scan on\r"
expect $device
send -- "connect $device\r"
expect "ServicesResolved: yes"
send -- "scan off\r"
expect "Discovering: no"
send -- "menu gatt\r"
expect "Menu gatt:"
send -- "select-attribute $uuid\r"
expect "service"
send -- "read\r"
expect "Attribute"
send -- "back\r"
expect "Menu main:"
send -- "disconnect\r"
expect "disconnected"